### ISSUE TITLE
[1.15.0 Beta] Pointer not aligned

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-editor#241]
![image](https://user-images.githubusercontent.com/5925563/134239005-ac139406-da0c-4207-a3e6-4df38cd9ec97.png)

**Comment by jamesros161** [comment]
I don't see that issue when loading the editor. This is how it appears for me:
![image](https://user-images.githubusercontent.com/49331357/134373844-7b0ce861-0b08-454d-8987-6382fb4073f6.png)

**Comment by nicolepaschen** [comment]
James: It's the Admin Notices doing it!
